### ISSUE TITLE
BUG/ERROR 

### ISSUE THREAD

**Issue by pandathebeasty** [Muinez/CSSModularity#2]
Sometimes the plugin is throwing an error:
19:14:01 [EROR] (plugin:Modularity) Cant find System.IO.MemoryMappedFiles.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
19:14:01 [EROR] (plugin:Modularity) Cant find Microsoft.CSharp.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a

Can you have a look?

**Comment by Muinez** [comment]
> Sometimes the plugin is throwing an error: 19:14:01 [EROR] (plugin:Modularity) Cant find System.IO.MemoryMappedFiles.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a 19:14:01 [EROR] (plugin:Modularity) Cant find Microsoft.CSharp.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
> 
> Can you have a look?

is everything working fine after these errors?

**Comment by pandathebeasty** [comment]
> > Sometimes the plugin is throwing an error: 19:14:01 [EROR] (plugin:Modularity) Cant find System.IO.MemoryMappedFiles.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a 19:14:01 [EROR] (plugin:Modularity) Cant find Microsoft.CSharp.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
> > Can you have a look?
> 
> is everything working fine after these errors?

not really, after updating to c# V142 
:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/ModularityPlugin/ModularityPlugin.dll
CounterStrikeSharp.API.Core.NativeException: Global Variables not initialized yet.
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.GetMaxClients() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 320
   at CounterStrikeSharp.API.Server.get_MaxPlayers() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Server.cs:line 78
   at VIP_RainbowModel.VipRainbowModel..ctor() in D:\CSS\cs2-VIPCore-1.0.4\VIPCore\modules\VIP_RainbowModel\VIP_RainbowModel.cs:line 19
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 189
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52
   at ModularityPlugin.ModularityPlugin.Load(Boolean hotReload) in G:\images\images\Modularity\ModularityPlugin\ModularityPlugin.cs:line 54
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 201
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 34
   
   LE: nvm related to other modular plugin
   
   and related to your question, I think it works normally

**Comment by Muinez** [comment]
check out the latest release

**Comment by pandathebeasty** [comment]
hello
14:26:52 [EROR] (plugin:Modularity) Cant find YamlDotNet, Version=9.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e
14:26:52 [EROR] (plugin:Modularity) Cant find MySqlConnector, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92
14:26:52 [EROR] (plugin:Modularity) Cant find Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
14:26:52 [EROR] (plugin:Modularity) Cant find Dapper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
14:26:52 [EROR] (plugin:Modularity) Cant find MySqlConnector, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92

with csharp v168 these new errors appeared
